name: room_check_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# 애플리케이션 의존성
dependencies:
  flutter:
    sdk: flutter
  image: ^4.1.7
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+2
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  flutter_dotenv: ^5.0.5
  dash_chat_2: ^0.0.20 # 채팅 UI 패키지
  http: ^1.2.1

# 개발용 의존성
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

# Flutter 관련 설정
flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.test